# Generated by Django 5.0.1 on 2024-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('1', 'Languages'), ('2', 'Programming')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
